  server:
    port: 8080

  spring:
    datasource:
      username: root
      password: anezer200
      url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    jpa:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: create
      show-sql: true


  # example value

  indexing-settings:
    sites:
      - url: https://sendel.ru/
        name: sendel.ru
      - url:  https://nikoartgallery.com/
        name: nikoartgallery.com



